apiVersion: v1
kind: Secret
metadata:
  name: awssm-secret
  namespace: fiap
type: Opaque
data:
  access-key: $(base64 -w 0 <<< "$AWS_ACCESS_KEY_ID")
  secret-access-key: $(base64 -w 0 <<< "$AWS_SECRET_ACCESS_KEY")
  session-token: $(base64 -w 0 <<< "$AWS_SESSION_TOKEN")

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: restaurante-acme-secretstore
  namespace: fiap
spec:
  provider:
    aws:
      service: SecretsManager
      # define a specific role to limit access
      # to certain secrets.
      # role is a optional field that
      # can be omitted for test purposes
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
            namespace: fiap
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
            namespace: fiap
          sessionTokenSecretRef:
            name: awssm-secret
            key: session-token
            namespace: fiap

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: restaurante-acme-secrets
  namespace: fiap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: restaurante-acme-secretstore
  dataFrom:
    - extract:
        key: fiap/restaurante-acme-secrets
    - extract:
        key: fiap/restaurante-acme-database
  refreshInterval: 5m
  target:
    creationPolicy: Owner
    deletionPolicy: Retain

